name: CI => create a PR (Tests -> PR -> enable auto-merge)

on:
  push:
    branches:
      - 'main'
      - 'feature/**'
  pull_request:
    branches:
      - 'main'

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs: 
  build-and-test:
    name: build-and-test
    runs-on: ubuntu-latest   # corregido el typo
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
          
      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Test all projects
        run: dotnet test ./Solution.sln --configuration Release --verbosity normal

  create-pr:
    name: create-pr-if-tests-pass
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Create PR if none exists
        id: create_pr
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT_TOKEN }}   # <- usamos el PAT guardado
          script: |
            const branch = process.env.GITHUB_REF.replace('refs/heads/','');
            const base = 'main';
            // buscar PR abierta desde esta rama hacia main
            const { data: prs } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: `${context.repo.owner}:${branch}`,
              base,
              state: 'open'
            });
            if (prs.length > 0) {
              console.log(`PR already exists: ${prs[0].html_url}`);
              return prs[0].number;
            }
            // crear PR
            const pr = await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: branch,
              base,
              title: `Feature / ${branch}`,
              body: `PR auto-creado por CI: las pruebas pasaron. Por favor revisar y aprobar.`,
            });
            console.log(`Created PR: ${pr.data.html_url}`);
            return pr.data.number;


